version: '3.4'

services:
  selenium_hub:
    image: selenium/hub:4.0.0-beta-1-20210215
    environment:
      GRID_THROW_ON_CAPABILITY_NOT_PRESENT: 'false'
      GRID_MAX_SESSION: 10
      GRID_BROWSER_TIMEOUT: 100000
      GRID_TIMEOUT: 90000
      GRID_NEW_SESSION_WAIT_TIMEOUT: 150000
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      replicas: 1
    environment:
      HUB_HOST: selenium_hub
      HUB_PORT: 4444
      SE_EVENT_BUS_HOST: selenium_hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1
      TZ: 'America/Chicago'
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'

  firefox:
    image: selenium/node-firefox:4.0.0-beta-1-20210215
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      replicas: 1
    environment:
      HUB_HOST: selenium_hub
      HUB_PORT: 4444
      SE_EVENT_BUS_HOST: selenium_hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      NODE_MAX_SESSION: 1
      NODE_MAX_INSTANCES: 1
      TZ: 'America/Chicago'
    entrypoint: bash -c 'SE_OPTS="-host $$HOSTNAME" /opt/bin/entry_point.sh'
